---
guhcampos_tf_download_dir: "{{ansible_user_dir}}/.local/tmp"
guhcampos_tf_install_dir: "{{ansible_user_dir}}/.local/bin"

guhcampos_tf_versions:
  - version: "1.5.7"
    arch: "arm64"
    checksum: "sha256:db7c33eb1a446b73a443e2c55b532845f7b70cd56100bec4c96f15cfab5f50cb"
    system: "darwin"

  - version: "1.6.2"
    arch: "arm64"
    checksum: "sha256:87345e9f2932c29c8d00c5ca9e0361fada18accc2573fd66883b3adb40949be8"
    system: "darwin"

  - version: "1.5.7"
    arch: "amd64"
    checksum: "sha256:"
    system: "linux"

  - version: "1.6.2"
    arch: "amd64"
    checksum: "sha256:"
    system: "linux"

guhcampos_tf_default_version: 1.5.7
guhcampos_tf_base_url: "https://releases.hashicorp.com/terraform/"
guhcampos_tf_download_url: "{{guhcampos_tf_base_url}}{{item.version}}/terraform_{{item.version}}_{{item.system}}_{{item.arch}}.zip"
# https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_darwin_arm64.zip
