#!/bin/bash

source /etc/profile

export GUHCAMPOS_ERROR_LOG="$HOME/guhcampos-errors.log"

# some of my setup depends on the existence of pyenv, this ensures it's properly
# detected if it's available in the system, we will setup it later in the script
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"

if [ -e "$HOME/.config/bash.d" ]; then
    for lib in "$HOME"/.config/bash.d/*.sh; do
        # shellcheck disable=SC1090
        source "$lib"
    done
fi

export XDG_CONFIG_HOME="${HOME}/.config"
export GUH_LOADED_BASHRC
