let g:solarized_termtrans = 1
let g:solarized_visibility = "high"
let g:solarized_contrast = "high"

set background=dark
colorscheme monokai

syntax enable

set t_Co=256
set nu
set sm
set cindent
set wildmode=longest,list
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set termencoding=utf8
set nobackup


" execute pathogen#infect()
" set nocompatible          " get rid of Vi compatibility mode. SET FIRST!
" let base16colorspace=256
" filetype on
" filetype indent on        " activates indenting for files
" filetype plugin indent on " filetype detection[ON] plugin[ON] indent[ON]
" set t_Co=256              " enable 256-color mode.
" syntax enable             " enable syntax highlighting (previously syntax on).
" set number                " show line numbers
" set laststatus=2          " last window always has a statusline
" set hlsearch              " Don't continue to highlight searched phrases.
" set incsearch             " But do highlight as you type your search.
" set ruler                 " Always show info along bottom.
" set autoindent            " auto-indent
" set tabstop=4             " tab spacing
" set softtabstop=4         " unify
" set shiftwidth=4          " indent/outdent by 4 columns
" set shiftround            " always indent/outdent to the nearest tabstop
" set expandtab             " use spaces instead of tabs
" set smarttab              " use tabs at the start of a line, spaces elsewhere
" set nowrap                " don't wrap text
" set nobackup
" set termencoding=utf8
" set sm
" set cindent
" set wildmode=longest,list
" set nofoldenable
" colorscheme base16-one-light
