---
- name: Install Debian applications with `apt`
  ansible.builtin.apt:
    pkg: "{{item}}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  loop: "{{shell_debian_apps_apt}}"
  become: true
  become_user: root

- name: Install Debian applications with `cargo`
  community.general.cargo:
    name: "{{item}}"
    path: /usr/local
    locked: true
  loop: "{{shell_debian_apps_cargo}}"
  become: true
  become_user: root

- name: Install `yq` on Debian
  ansible.builtin.get_url:
    url: "{{yq_download_path}}"
    dest: "/usr/local/bin/yq"
    mode: "0555"
