---
# - name: install bash-completion
#   community.general.homebrew:
#     name: bash-completion
#     state: latest
#   when: ansible_facts['os_family'] == "Darwin"

- name: create missing directories for dotfiles
  ansible.builtin.file:
    path: "{{ansible_env.HOME}}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  tags: [dotfiles]
  with_community.general.filetree: "home"
  when: item.state == 'directory'

- name: link dotfiles to their respective directories
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ansible_env.HOME}}/{{ item.path }}"
    state: link
  tags: [dotfiles]
  with_community.general.filetree: "home"
  when: item.state == 'file'

- name: "including platform specific tasks: [Debian]"
  when: ansible_facts['os_family'] == "Debian"
  ansible.builtin.import_tasks: _debian.yaml

- name: "including platform specific tasks: [Darwin]"
  when: ansible_facts['os_family'] == "Darwin"
  ansible.builtin.import_tasks: _darwin.yaml

- name: "Install python applications with pipx"
  community.general.pipx:
    name: "{{item}}"
    state: latest
  loop: "{{shell_apps_pipx}}"
