---
- name: block execution of the role on remote servers
  ansible.builtin.fail:
    msg: this role is only intended for use on a local machine
  when: ansible_connection != "local"

- name: create missing directories for dotfiles
  ansible.builtin.file:
    path: "{{ansible_env.HOME}}/{{ item.path }}"
    state: directory
    mode: "{{ item.mode }}"
  tags: [dotfiles]
  with_community.general.filetree: "home"
  when: item.state == 'directory'

- name: link dotfiles to their respective directories
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ansible_env.HOME}}/{{ item.path }}"
    state: link
    force: "{{shell_force_symlinks}}"
  tags: [dotfiles]
  with_community.general.filetree: "home"
  when: item.state == 'file'

- name: "including platform specific tasks: [Debian]"
  when: ansible_facts['os_family'] == "Debian"
  ansible.builtin.import_tasks: _debian.yaml

- name: "including platform specific tasks: [Darwin]"
  when: ansible_facts['os_family'] == "Darwin"
  ansible.builtin.import_tasks: _darwin.yaml

- name: install system-wide python packages
  ansible.builtin.pip:
    name: "{{item}}"
  loop: "{{shell_system_python_packages}}"
  tags: [python]
